name: Deployment status
on: deployment_status

env:
  CIRCLE_PROJECT_SLUG: github/SpeechKit/speechkit-audio-player-v2
  CIRCLE_API_TOKEN: ${{ secrets.CIRCLE_API_TOKEN }}
  DEPLOYMENT_BRANCH: ${{ github.event.deployment.payload.branch }}

jobs:
  trigger-tests:
    name: Trigger tests
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.description == 'Run tests'
    steps:
      - name: Trigger pipeline on CircleCI
        run: |
          TRIGGER_BODY="$(cat <<-EOF
          {
            "branch": "$DEPLOYMENT_BRANCH",
            "parameters": {
              "run_tests": true,
            }
          }
          EOF
          )"
          echo "Triggering new pipeline in $CIRCLE_PROJECT_SLUG with the following parameters: $TRIGGER_BODY"
          curl -f -s -X POST "https://circleci.com/api/v2/project/$CIRCLE_PROJECT_SLUG/pipeline?circle-token=$CIRCLE_API_TOKEN" \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -d "$TRIGGER_BODY"
